services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - my-network
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - my-network
    command:
      [
        "./wait-for-it.sh",
        "db:3306",
        "--",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
